//! 写出 LVGL `lv_font_t` C 源文件。

use super::cmap::CmapEntry;
use super::Glyph;

fn escape_comment_char(cp: u32) -> String {
    if cp == 0x5C {
        return "\\\\".into();
    }
    if cp == 0x22 {
        return "\\\"".into();
    }
    if (0x20..=0x7E).contains(&cp) && cp != 0x2A {
        return char::from_u32(cp).unwrap().to_string();
    }
    if let Some(ch) = char::from_u32(cp) {
        if !ch.is_control() && ch != '*' && ch != '/' {
            return ch.to_string();
        }
    }
    format!("\\u{cp:04x}")
}

/// `on_progress(written_glyphs, total_glyphs)`
pub fn write_lvgl_c(
    font_name: &str,
    opts: &str,
    bpp: u8,
    size: u32,
    glyphs: &[Glyph],
    cmaps: &[CmapEntry],
    line_height: i32,
    base_line: i32,
    lv_include: &str,
    fallback: &str,
    mut on_progress: impl FnMut(u32, u32),
) -> Result<String, String> {
    let guard = font_name.to_ascii_uppercase();
    let total = glyphs.len() as u32;
    // 预估容量：每个字形约 80+ 字节注释/描述 + bitmap hex
    let mut est = 8 * 1024;
    for g in glyphs {
        est += 64 + g.bitmap.len() * 6;
    }
    let mut out = String::with_capacity(est);
    let w = &mut out;

    w.push_str("/*******************************************************************************\n");
    w.push_str(" * Generated by Wheat ESP Tools\n");
    w.push_str(&format!(" * Size: {size} px\n"));
    w.push_str(&format!(" * Bpp: {bpp}\n"));
    w.push_str(&format!(" * Opts: {opts}\n"));
    w.push_str(" ******************************************************************************/\n\n");

    w.push_str("#ifdef LV_LVGL_H_INCLUDE_SIMPLE\n");
    w.push_str(&format!("#include \"{lv_include}\"\n"));
    w.push_str("#else\n");
    w.push_str(&format!("#include \"{lv_include}\"\n"));
    w.push_str("#endif\n\n");

    w.push_str(&format!("#ifndef {guard}\n#define {guard} 1\n#endif\n\n#if {guard}\n\n"));

    // BITMAPS
    w.push_str("/*-----------------\n *    BITMAPS\n *----------------*/\n\n");
    w.push_str("/*Store the image of the glyphs*/\n");
    w.push_str("static LV_ATTRIBUTE_LARGE_CONST const uint8_t glyph_bitmap[] = {\n");

    let mut bitmap_index = Vec::with_capacity(glyphs.len() + 1);
    bitmap_index.push(0u32); // id0
    let mut bitmap_off: u32 = 0;

    for (idx, g) in glyphs.iter().enumerate() {
        bitmap_index.push(bitmap_off);
        let comment = escape_comment_char(g.cp);
        w.push_str(&format!("    /* U+{:04X} \"{comment}\" */\n", g.cp));
        let data = &g.bitmap;
        let mut i = 0;
        while i < data.len() {
            let end = (i + 8).min(data.len());
            let hexes: Vec<String> = data[i..end]
                .iter()
                .map(|b| format!("0x{b:02x}"))
                .collect();
            w.push_str("    ");
            w.push_str(&hexes.join(", "));
            w.push_str(",\n");
            i = end;
        }
        w.push('\n');
        bitmap_off = bitmap_off
            .checked_add(data.len() as u32)
            .ok_or_else(|| "位图偏移溢出，字形过多或过大".to_string())?;

        let written = (idx as u32) + 1;
        if written == 1 || written == total || written % 200 == 0 {
            on_progress(written, total.max(1));
        }
    }
    w.push_str("};\n\n");

    // GLYPH DSC
    w.push_str("/*-----------------\n *    GLYPH DESCRIPTION\n *----------------*/\n\n");
    w.push_str("static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {\n");
    w.push_str(
        "    {.bitmap_index = 0, .adv_w = 0, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0} /* id = 0 reserved */,\n",
    );
    for (idx, g) in glyphs.iter().enumerate() {
        let bi = bitmap_index[idx + 1];
        w.push_str(&format!(
            "    {{.bitmap_index = {bi}, .adv_w = {}, .box_w = {}, .box_h = {}, .ofs_x = {}, .ofs_y = {}}},\n",
            g.adv_w, g.box_w, g.box_h, g.ofs_x, g.ofs_y
        ));
    }
    w.push_str("};\n\n");

    // CHARACTER MAPPING
    w.push_str("/*-----------------\n *    CHARACTER MAPPING\n *----------------*/\n\n");
    for cm in cmaps {
        if cm.type_name == "SPARSE_TINY" {
            if let (Some(list), Some(name)) = (&cm.unicode_list, &cm.list_name) {
                w.push_str(&format!("static const uint16_t {name}[] = {{\n"));
                for chunk in list.chunks(16) {
                    w.push_str("    ");
                    w.push_str(
                        &chunk
                            .iter()
                            .map(|x| x.to_string())
                            .collect::<Vec<_>>()
                            .join(", "),
                    );
                    w.push_str(",\n");
                }
                w.push_str("};\n\n");
            }
        }
    }

    w.push_str("/*Collect the map of the glyph's unicode start & end->glyph_id start & end*/\n");
    w.push_str("static const lv_font_fmt_txt_cmap_t cmaps[] = {\n");
    for cm in cmaps {
        if cm.type_name == "FORMAT0_TINY" {
            w.push_str(&format!(
                "    {{\n\
                 \x20       .range_start = {}, .range_length = {}, .glyph_id_start = {},\n\
                 \x20       .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0, .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY\n\
                 \x20   }},\n",
                cm.range_start, cm.range_length, cm.glyph_id_start
            ));
        } else {
            let name = cm.list_name.as_deref().unwrap_or("NULL");
            let len = cm.unicode_list.as_ref().map(|l| l.len()).unwrap_or(0);
            w.push_str(&format!(
                "    {{\n\
                 \x20       .range_start = {}, .range_length = {}, .glyph_id_start = {},\n\
                 \x20       .unicode_list = {name}, .glyph_id_ofs_list = NULL, .list_length = {len}, .type = LV_FONT_FMT_TXT_CMAP_SPARSE_TINY\n\
                 \x20   }},\n",
                cm.range_start, cm.range_length, cm.glyph_id_start
            ));
        }
    }
    w.push_str("};\n\n");

    // FONT DSC
    w.push_str("/*--------------------\n *  ALL CUSTOM DATA\n *--------------------*/\n\n");
    w.push_str("#if LVGL_VERSION_MAJOR == 8\n");
    w.push_str("/*Store all the custom data of the font*/\n");
    w.push_str("static  lv_font_fmt_txt_glyph_cache_t cache;\n");
    w.push_str("#endif\n\n");
    w.push_str("#if LVGL_VERSION_MAJOR >= 8\n");
    w.push_str("static const lv_font_fmt_txt_dsc_t font_dsc = {\n");
    w.push_str("#else\n");
    w.push_str("static lv_font_fmt_txt_dsc_t font_dsc = {\n");
    w.push_str("#endif\n");
    w.push_str("    .glyph_bitmap = glyph_bitmap,\n");
    w.push_str("    .glyph_dsc = glyph_dsc,\n");
    w.push_str("    .cmaps = cmaps,\n");
    w.push_str("    .kern_dsc = NULL,\n");
    w.push_str("    .kern_scale = 0,\n");
    w.push_str(&format!("    .cmap_num = {},\n", cmaps.len()));
    w.push_str(&format!("    .bpp = {bpp},\n"));
    w.push_str("    .kern_classes = 0,\n");
    w.push_str("    .bitmap_format = 0,\n");
    w.push_str("#if LVGL_VERSION_MAJOR == 8\n");
    w.push_str("    .cache = &cache\n");
    w.push_str("#endif\n");
    w.push_str("};\n\n\n\n");

    // PUBLIC FONT
    w.push_str("/*-----------------\n *  PUBLIC FONT\n *----------------*/\n\n");
    w.push_str("/*Initialize a public general font descriptor*/\n");
    w.push_str("#if LVGL_VERSION_MAJOR >= 8\n");
    w.push_str(&format!("const lv_font_t {font_name} = {{\n"));
    w.push_str("#else\n");
    w.push_str(&format!("lv_font_t {font_name} = {{\n"));
    w.push_str("#endif\n");
    w.push_str("    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,\n");
    w.push_str("    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,\n");
    w.push_str(&format!("    .line_height = {line_height},\n"));
    w.push_str(&format!("    .base_line = {base_line},\n"));
    w.push_str("#if !(LVGL_VERSION_MAJOR == 6 && LVGL_VERSION_MINOR == 0)\n");
    w.push_str("    .subpx = LV_FONT_SUBPX_NONE,\n");
    w.push_str("#endif\n");
    w.push_str("#if LV_VERSION_CHECK(7, 4, 0) || LVGL_VERSION_MAJOR >= 8\n");
    w.push_str("    .underline_position = -1,\n");
    w.push_str("    .underline_thickness = 1,\n");
    w.push_str("#endif\n");
    w.push_str("    .dsc = &font_dsc,\n");
    w.push_str("#if LV_VERSION_CHECK(8, 2, 0) || LVGL_VERSION_MAJOR >= 9\n");
    if fallback.is_empty() {
        w.push_str("    .fallback = NULL,\n");
    } else {
        w.push_str(&format!("    .fallback = &{fallback},\n"));
    }
    w.push_str("#endif\n");
    w.push_str("    .user_data = NULL,\n");
    w.push_str("};\n\n\n\n");
    w.push_str(&format!("#endif /*#if {guard}*/\n"));

    on_progress(total.max(1), total.max(1));
    Ok(out)
}
