//! 写出 LVGL `lv_font_t` C 源文件。

use super::cmap::CmapEntry;
use super::Glyph;

fn escape_comment_char(cp: u32) -> String {
    if cp == 0x5C {
        return "\\\\".into();
    }
    if cp == 0x22 {
        return "\\\"".into();
    }
    if (0x20..=0x7E).contains(&cp) && cp != 0x2A {
        return char::from_u32(cp).unwrap().to_string();
    }
    if let Some(ch) = char::from_u32(cp) {
        if !ch.is_control() && ch != '*' && ch != '/' {
            return ch.to_string();
        }
    }
    format!("\\u{cp:04x}")
}

/// 避免用户输入破坏 C 块注释（如 `*/`）。
fn sanitize_comment_text(s: &str) -> String {
    s.replace("*/", "* /").replace('\n', " ").replace('\r', "")
}

/// 写入文件头用的人类可读转换参数（非 CLI 风格）。
pub struct LvglHeaderInfo<'a> {
    pub source_font: &'a str,
    pub font_name: &'a str,
    pub size: u32,
    pub bpp: u8,
    pub range: &'a str,
    pub symbols: &'a str,
    pub lv_include: &'a str,
    pub fallback: &'a str,
    pub glyph_count: u32,
}

fn write_file_header(w: &mut String, info: &LvglHeaderInfo<'_>) {
    let src = sanitize_comment_text(info.source_font);
    let name = sanitize_comment_text(info.font_name);
    let include = sanitize_comment_text(info.lv_include);
    let range = sanitize_comment_text(info.range.trim());
    let symbols = sanitize_comment_text(info.symbols);
    let fallback = sanitize_comment_text(info.fallback.trim());
    let generated_at = local_now_string();

    w.push_str("/*******************************************************************************\n");
    w.push_str(" * Generated by Wheat ESP Tools — LVGL Font Converter\n");
    w.push_str(&format!(" * Generated at : {generated_at}\n"));
    w.push_str(" *\n");
    w.push_str(&format!(" *   Source font : {src}\n"));
    w.push_str(&format!(" *   C symbol    : {name}\n"));
    w.push_str(&format!(" *   Output file : {name}.c\n"));
    w.push_str(&format!(" *   Pixel size  : {} px\n", info.size));
    w.push_str(&format!(" *   Bits/pixel  : {}\n", info.bpp));
    w.push_str(&format!(" *   Glyph count : {}\n", info.glyph_count));
    if !range.is_empty() {
        w.push_str(&format!(" *   Unicode     : {range}\n"));
    }
    if !symbols.is_empty() {
        w.push_str(&format!(" *   Symbols     : {symbols}\n"));
    }
    w.push_str(&format!(" *   Include     : {include}\n"));
    if !fallback.is_empty() {
        w.push_str(&format!(" *   Fallback    : {fallback}\n"));
    }
    w.push_str(" *\n");
    w.push_str(" *   Style        : uncompressed bitmap, no kerning, no subpixel\n");
    w.push_str(" ******************************************************************************/\n\n");
}

/// 本地时间，格式 `YYYY-MM-DD HH:MM:SS`。
fn local_now_string() -> String {
    #[cfg(windows)]
    {
        use std::mem::MaybeUninit;
        #[repr(C)]
        struct SystemTimeWin {
            year: u16,
            month: u16,
            day_of_week: u16,
            day: u16,
            hour: u16,
            minute: u16,
            second: u16,
            milliseconds: u16,
        }
        extern "system" {
            fn GetLocalTime(lp_system_time: *mut SystemTimeWin);
        }
        let mut st = MaybeUninit::<SystemTimeWin>::uninit();
        unsafe {
            GetLocalTime(st.as_mut_ptr());
            let st = st.assume_init();
            return format!(
                "{:04}-{:02}-{:02} {:02}:{:02}:{:02}",
                st.year, st.month, st.day, st.hour, st.minute, st.second
            );
        }
    }
    #[cfg(not(windows))]
    {
        use std::time::{SystemTime, UNIX_EPOCH};
        let Ok(dur) = SystemTime::now().duration_since(UNIX_EPOCH) else {
            return "unknown".into();
        };
        let secs = dur.as_secs() as i64;
        let days = secs.div_euclid(86400);
        let tod = secs.rem_euclid(86400) as u32;
        let hour = tod / 3600;
        let min = (tod % 3600) / 60;
        let sec = tod % 60;
        let z = days + 719468;
        let era = if z >= 0 { z } else { z - 146096 } / 146097;
        let doe = (z - era * 146097) as u32;
        let yoe = (doe - doe / 1460 + doe / 36524 - doe / 146096) / 365;
        let y = yoe as i64 + era * 400;
        let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
        let mp = (5 * doy + 2) / 153;
        let d = doy - (153 * mp + 2) / 5 + 1;
        let m = if mp < 10 { mp + 3 } else { mp - 9 };
        let y = if m <= 2 { y + 1 } else { y };
        format!("{y:04}-{m:02}-{d:02} {hour:02}:{min:02}:{sec:02} UTC")
    }
}

/// `on_progress(written_glyphs, total_glyphs)`
pub fn write_lvgl_c(
    header: &LvglHeaderInfo<'_>,
    glyphs: &[Glyph],
    cmaps: &[CmapEntry],
    line_height: i32,
    base_line: i32,
    mut on_progress: impl FnMut(u32, u32),
) -> Result<String, String> {
    let font_name = header.font_name;
    let bpp = header.bpp;
    let lv_include = header.lv_include;
    let fallback = header.fallback;
    let guard = font_name.to_ascii_uppercase();
    let total = glyphs.len() as u32;
    // 预估容量：每个字形约 80+ 字节注释/描述 + bitmap hex
    let mut est = 8 * 1024;
    for g in glyphs {
        est += 64 + g.bitmap.len() * 6;
    }
    let mut out = String::with_capacity(est);
    let w = &mut out;

    write_file_header(w, header);

    w.push_str("#ifdef LV_LVGL_H_INCLUDE_SIMPLE\n");
    w.push_str("#include \"lvgl.h\"\n");
    w.push_str("#else\n");
    // 默认 lvgl.h → lvgl/lvgl.h；用户自定义路径原样使用
    if lv_include == "lvgl.h" {
        w.push_str("#include \"lvgl/lvgl.h\"\n");
    } else {
        w.push_str(&format!("#include \"{lv_include}\"\n"));
    }
    w.push_str("#endif\n\n");

    w.push_str(&format!("#ifndef {guard}\n#define {guard} 1\n#endif\n\n#if {guard}\n\n"));

    // BITMAPS
    w.push_str("/*-----------------\n *    BITMAPS\n *----------------*/\n\n");
    w.push_str("/*Store the image of the glyphs*/\n");
    w.push_str("static LV_ATTRIBUTE_LARGE_CONST const uint8_t glyph_bitmap[] = {\n");

    let mut bitmap_index = Vec::with_capacity(glyphs.len() + 1);
    bitmap_index.push(0u32); // id0
    let mut bitmap_off: u32 = 0;

    for (idx, g) in glyphs.iter().enumerate() {
        bitmap_index.push(bitmap_off);
        let comment = escape_comment_char(g.cp);
        w.push_str(&format!("    /* U+{:04X} \"{comment}\" */\n", g.cp));
        let data = &g.bitmap;
        let mut i = 0;
        while i < data.len() {
            let end = (i + 8).min(data.len());
            let hexes: Vec<String> = data[i..end]
                .iter()
                .map(|b| format!("0x{b:02x}"))
                .collect();
            w.push_str("    ");
            w.push_str(&hexes.join(", "));
            w.push_str(",\n");
            i = end;
        }
        w.push('\n');
        bitmap_off = bitmap_off
            .checked_add(data.len() as u32)
            .ok_or_else(|| "位图偏移溢出，字形过多或过大".to_string())?;

        let written = (idx as u32) + 1;
        if written == 1 || written == total || written % 200 == 0 {
            on_progress(written, total.max(1));
        }
    }
    w.push_str("};\n\n");

    // GLYPH DSC
    w.push_str("/*-----------------\n *    GLYPH DESCRIPTION\n *----------------*/\n\n");
    w.push_str("static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {\n");
    w.push_str(
        "    {.bitmap_index = 0, .adv_w = 0, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0} /* id = 0 reserved */,\n",
    );
    for (idx, g) in glyphs.iter().enumerate() {
        let bi = bitmap_index[idx + 1];
        w.push_str(&format!(
            "    {{.bitmap_index = {bi}, .adv_w = {}, .box_w = {}, .box_h = {}, .ofs_x = {}, .ofs_y = {}}},\n",
            g.adv_w, g.box_w, g.box_h, g.ofs_x, g.ofs_y
        ));
    }
    w.push_str("};\n\n");

    // CHARACTER MAPPING
    w.push_str("/*-----------------\n *    CHARACTER MAPPING\n *----------------*/\n\n");
    for cm in cmaps {
        if cm.type_name == "SPARSE_TINY" {
            if let (Some(list), Some(name)) = (&cm.unicode_list, &cm.list_name) {
                w.push_str(&format!("static const uint16_t {name}[] = {{\n"));
                for chunk in list.chunks(16) {
                    w.push_str("    ");
                    w.push_str(
                        &chunk
                            .iter()
                            .map(|x| x.to_string())
                            .collect::<Vec<_>>()
                            .join(", "),
                    );
                    w.push_str(",\n");
                }
                w.push_str("};\n\n");
            }
        }
    }

    w.push_str("/*Collect the map of the glyph's unicode start & end->glyph_id start & end*/\n");
    w.push_str("static const lv_font_fmt_txt_cmap_t cmaps[] = {\n");
    for cm in cmaps {
        if cm.type_name == "FORMAT0_TINY" {
            w.push_str(&format!(
                "    {{\n\
                 \x20       .range_start = {}, .range_length = {}, .glyph_id_start = {},\n\
                 \x20       .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0, .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY\n\
                 \x20   }},\n",
                cm.range_start, cm.range_length, cm.glyph_id_start
            ));
        } else {
            let name = cm.list_name.as_deref().unwrap_or("NULL");
            let len = cm.unicode_list.as_ref().map(|l| l.len()).unwrap_or(0);
            w.push_str(&format!(
                "    {{\n\
                 \x20       .range_start = {}, .range_length = {}, .glyph_id_start = {},\n\
                 \x20       .unicode_list = {name}, .glyph_id_ofs_list = NULL, .list_length = {len}, .type = LV_FONT_FMT_TXT_CMAP_SPARSE_TINY\n\
                 \x20   }},\n",
                cm.range_start, cm.range_length, cm.glyph_id_start
            ));
        }
    }
    w.push_str("};\n\n");

    // FONT DSC
    w.push_str("/*--------------------\n *  ALL CUSTOM DATA\n *--------------------*/\n\n");
    w.push_str("#if LVGL_VERSION_MAJOR == 8\n");
    w.push_str("/*Store all the custom data of the font*/\n");
    w.push_str("static  lv_font_fmt_txt_glyph_cache_t cache;\n");
    w.push_str("#endif\n\n");
    w.push_str("#if LVGL_VERSION_MAJOR >= 8\n");
    w.push_str("static const lv_font_fmt_txt_dsc_t font_dsc = {\n");
    w.push_str("#else\n");
    w.push_str("static lv_font_fmt_txt_dsc_t font_dsc = {\n");
    w.push_str("#endif\n");
    w.push_str("    .glyph_bitmap = glyph_bitmap,\n");
    w.push_str("    .glyph_dsc = glyph_dsc,\n");
    w.push_str("    .cmaps = cmaps,\n");
    w.push_str("    .kern_dsc = NULL,\n");
    w.push_str("    .kern_scale = 0,\n");
    w.push_str(&format!("    .cmap_num = {},\n", cmaps.len()));
    w.push_str(&format!("    .bpp = {bpp},\n"));
    w.push_str("    .kern_classes = 0,\n");
    w.push_str("    .bitmap_format = 0,\n");
    w.push_str("#if LVGL_VERSION_MAJOR == 8\n");
    w.push_str("    .cache = &cache\n");
    w.push_str("#endif\n");
    w.push_str("};\n\n\n\n");

    // PUBLIC FONT
    w.push_str("/*-----------------\n *  PUBLIC FONT\n *----------------*/\n\n");
    w.push_str("/*Initialize a public general font descriptor*/\n");
    w.push_str("#if LVGL_VERSION_MAJOR >= 8\n");
    w.push_str(&format!("const lv_font_t {font_name} = {{\n"));
    w.push_str("#else\n");
    w.push_str(&format!("lv_font_t {font_name} = {{\n"));
    w.push_str("#endif\n");
    w.push_str("    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,\n");
    w.push_str("    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,\n");
    w.push_str(&format!("    .line_height = {line_height},\n"));
    w.push_str(&format!("    .base_line = {base_line},\n"));
    w.push_str("#if !(LVGL_VERSION_MAJOR == 6 && LVGL_VERSION_MINOR == 0)\n");
    w.push_str("    .subpx = LV_FONT_SUBPX_NONE,\n");
    w.push_str("#endif\n");
    w.push_str("#if LV_VERSION_CHECK(7, 4, 0) || LVGL_VERSION_MAJOR >= 8\n");
    w.push_str("    .underline_position = -1,\n");
    w.push_str("    .underline_thickness = 1,\n");
    w.push_str("#endif\n");
    w.push_str("    .dsc = &font_dsc,\n");
    w.push_str("#if LV_VERSION_CHECK(8, 2, 0) || LVGL_VERSION_MAJOR >= 9\n");
    if fallback.is_empty() {
        w.push_str("    .fallback = NULL,\n");
    } else {
        w.push_str(&format!("    .fallback = &{fallback},\n"));
    }
    w.push_str("#endif\n");
    w.push_str("    .user_data = NULL,\n");
    w.push_str("};\n\n\n\n");
    w.push_str(&format!("#endif /*#if {guard}*/\n"));

    on_progress(total.max(1), total.max(1));
    Ok(out)
}
